### ISSUE TITLE
OlxAPIGetEquipment using TC_BRANCH yields undetermined results

### ISSUE THREAD

**Issue by TannerHollis** [aspeninc/TestBenchOlxAPI#2]
I have the following code using version 15.7.

```cpp
int handle = 0;
ret = OlxAPIGetEquipment(TC_BRANCH, &handle);
if(ret == OLXAPI_OK)
    cout << handle << endl;
```

which yields ` ret = -4 ` and ` handle = 0` unchanged. I am unable to populate branches and properly run faults using branches. However I can still run faults on bus objects.

From my understanding the return value should only be 1, 0, or -1.. However -4 is confusing me.

**Comment by aspeninc** [comment]
OlxAPIGetEquipment() is not designed to work with TC_BRANCH. 
nType can only be set to the equipment code for generators, shunts, loads, generating units, shunt units, load units, lines, series capacitors, transformers, phase shifters, switches, relay groups, overcurrent relays, fuses, distance relays, differential relays, voltage relays, reclosers and logic schemes:

https://www.aspeninc.com/man/ps15/index.html#!functiongetequipment.htm

You can use OlxAPIGetBusEquipment() and TC_BANCH to list all branches at the given bus:

https://www.aspeninc.com/man/ps15/index.html#!functiongetbusequipment.htm

**Comment by TannerHollis** [comment]
Thanks for the clarification, I guess it's a non-issue then.. I have a follow-up question then. Is there a simpler way to go from line (or branch type equipment) to branch handle of that the associated equipment?

#### My current workaround:
If I have the handle of the line, my current method for getting the branch handle is to use the nBus1Hnd from GetData using the bus handle and then then iterating over the resultant bus's equipment until I match the resultant equipment handle of each bus equipment. 

```cpp

/**
*   Return the associated branch Handle for a given device handle. Returns -1 if no branch is associated with the device
*/

int getLineBranchHandle(int lineHandle)
{
   int busHandle;
   int ret = OlxAPIGetData(lineHandle, LN_nBus1Hnd, &busHandle);
   if(ret != OLXAPI_OK)
       return ret; 
   
   int branchHandle = 0;
   int equipmentHandle = 0;
   while(ret == OLXAPI_OK)
   {
      ret = OlxAPIGetBusEquipment(busHandle, TC_BRANCH, &branchHandle);
      if(ret != OLXAPI_OK)
         break;
      
      ret = OlxAPIGetData(branchHandle, BR_nHandle, &equipmentHandle);
      if(ret != OLXAPI_OK)
         break;

      if(equipmentHandle == devHandle)
         return branchHandle;
   }

   return ret; // Not found
}

```

It's a bit much just to go from line -> branch. They only reason I have to go such route is because I cannot enumerate the branches like I can with lines, xfmrs, series capacitors, etc. If I could enumerate the branches using `OlxAPIGetEuipment`, then I have access to the equipment type and equipment handle from the branch handle. I could then build a map of each type using branch handles and go from there.

Is there a simpler way?

**Comment by aspeninc** [comment]
No. The method you are using is the only way.

I want to note that the TC_BRNACH object is designed to represent the connectors from a bus to all lines and transformers connected to it. TC_BRANCH is NOT meant to represent lines or transformers. In fact, there are exactly two TC_BRANCH objects for each line, one at each end bus.
